gen.PROJECT_URL=/Users/garellano/Desktop/development/desarrollo-ejercicio/
gen.SOURCE_URL=src/main/java/com/example/helloworld/

gen.AUTOR=Gustavo Arellano
gen.VERSION=1.0-SNAPSHOT
gen.NOMBRE_PROYECTO=ejemplo

gen.PACKAGE_BASE=com.example.helloworld

gen.DEFINITION_FOLDER=/Users/garellano/Desktop/generator-workspace/definitions/
       gen.TARGET_DIR=/Users/garellano/Desktop/generator-workspace/out2/
    gen.TEMPLATES_DIR=/Users/garellano/Desktop/generator-workspace/

